### ISSUE TITLE
Setup Chakra UI for Remix

### ISSUE THREAD

**Issue by Eakam1007** [Seneca-CDOT/starchart#24]
Building on top of #7, we would need to setup Chakra UI with Remix.
See [this Chakra UI docs page](https://chakra-ui.com/getting-started/remix-guide) for more information on setting up with Remix.

**Comment by Myrfion** [comment]
Hello @Eakam1007, Since #7  is done and was merged in #38 I would really appreciate it if you could prioritize delivering this issue since it blocks me from completing my issue for setting up the Charka UI theme and working on the front-end part in general. Thanks 

P.S. if you don't have the possibility to make it, just let me know and I could do it myself.

**Comment by humphd** [comment]
When I've done this, I used:

- https://chakra-ui.com/getting-started/remix-guide
- https://github.com/remix-run/examples/tree/main/chakra-ui

**Comment by Eakam1007** [comment]
I'll try to get it done by tomorrow evening
