### ISSUE TITLE
Design screen layouts

### ISSUE THREAD

**Issue by Myrfion** [Seneca-CDOT/starchart#58]
Design screens related to performing CRUD operations on subdomains via Figma layout.

https://www.figma.com/file/XAcnMIC1y4qumWinSalHI9/Starchart-UI?node-id=2105%3A2109&t=Q74PKVuk9bb4LkAd-1

**Comment by humphd** [comment]
@Myrfion @Ririio thank you for getting this design started.  Forgive me for not knowing the right way to do this Figma review (maybe I can do it in Figma?  I'm not sure.  Please educate me).

Here are my comments on what I see so far:

## Login Screen

https://www.figma.com/proto/XAcnMIC1y4qumWinSalHI9/Starchart-UI?node-id=2105%3A2112&scaling=min-zoom&page-id=2105%3A2109

https://www.figma.com/proto/XAcnMIC1y4qumWinSalHI9/Starchart-UI?node-id=2175%3A3563&scaling=min-zoom&page-id=2105%3A2109

I think we should give a 1 sentence explanation of what this is.  Maybe:

> Hello, Welcome to StarChart
> Create your own Custom Domains and SSL Certificates!

Also, Seneca is going to call their instance of this "My Custom Domain" as in https://mycustomdomain.senecacollege.ca.  So we should either use that name, or make "StarChart" a value we can set vs. hard code.

The second design above is doing more what I mean; however, we don't need "Create an Account"

## User Dashboard > Domains

https://www.figma.com/proto/XAcnMIC1y4qumWinSalHI9/Starchart-UI?node-id=2105%3A2126&scaling=min-zoom&page-id=2105%3A2109

I like the overall feel of this.  Some specifics to adjust:

1. Integrate sidebar menu into top menu.  So that we can more easily work on desktop/mobile, why don't we drop the sidebar menu.  It only has 2 items, so they could become links in the main nav bar instead.
2. "Domains" should probably be called "Custom Domains" and "Wildcart Certificates" should be "Certificates" (NOTE: we're going to create a wildcard certificate, but don't need to say that here).
3. The icon for "Certificates" should probably be Charkra's "LockIcon"
4. We won't have an avatar image for the user, so I would get rid of that.  We can show their name, or just a generic User Avatar icon if you need one.
5. In the Table of Domains, I would include buttons on the side of the items to Edit or Delete
6. In the Table, I would have the columns be: "Subdomain", "Type" (i.e., A, CNAME), and "Value" (i.e., what it points to, an IP or domain name).
7. Question: we have other data about a subdomain (when it expires, the course, description, ports, etc) that we need to be able to show some how.  Maybe we show it all here, or maybe you have to Edit or View the record to see it all (i.e., maybe this is just a summary view)?  cc @cychu42 for database aspect and @Genne23v for the DNS bits
8. We should probably standardize on "Domain" or "Subdomain," since this design is using both.

## User Dashboard > Create a new domain

https://www.figma.com/proto/XAcnMIC1y4qumWinSalHI9/Starchart-UI?node-id=2105%3A2403&scaling=min-zoom&page-id=2105%3A2109

1. Let's make our forms more accessible, using proper Labels.
2. I'd drop the left-hand icon on the field, it serves no purpose here (i.e. the React icon)
3. We need more fields cc @cychu42 for database input
4. We need a drop-down for the Type, one of CNAME Record, A Record, or AAAA Record.  We'll also need some text to explain what each one means, and how to choose

## User Dashboard > Edit existing domain

https://www.figma.com/proto/XAcnMIC1y4qumWinSalHI9/Starchart-UI?node-id=2105%3A2553&scaling=min-zoom&page-id=2105%3A2109

1. Need same fields as above
2. Need a button to Delete as well as Save
3. Need a button to Renew the domain (they will expire otherwise)

**Comment by Genne23v** [comment]
> 1. Integrate sidebar menu into top menu.  So that we can more easily work on desktop/mobile, why don't we drop the sidebar menu.  It only has 2 items, so they could become links in the main nav bar instead.
> 2. "Domains" should probably be called "Custom Domains" and "Wildcart Certificates" should be "Certificates" (NOTE: we're going to create a wildcard certificate, but don't need to say that here).
> 3. The icon for "Certificates" should probably be Charkra's "LockIcon"
> 4. We won't have an avatar image for the user, so I would get rid of that.  We can show their name, or just a generic User Avatar icon if you need one.
> 5. In the Table of Domains, I would include buttons on the side of the items to Edit or Delete
> 6. In the Table, I would have the columns be: "Subdomain", "Type" (i.e., A, CNAME), and "Value" (i.e., what it points to, an IP or domain name).
> 7. Question: we have other data about a subdomain (when it expires, the course, description, ports, etc) that we need to be able to show some how.  Maybe we show it all here, or maybe you have to Edit or View the record to see it all (i.e., maybe this is just a summary view)?  cc @cychu42 for database aspect and @Genne23v for the DNS bits
> 8. We should probably standardize on "Domain" or "Subdomain," since this design is using both.
> 
> ## User Dashboard > Create a new domain
> https://www.figma.com/proto/XAcnMIC1y4qumWinSalHI9/Starchart-UI?node-id=2105%3A2403&scaling=min-zoom&page-id=2105%3A2109
> 
> 1. Let's make our forms more accessible, using proper Labels.
> 2. I'd drop the left-hand icon on the field, it serves no purpose here (i.e. the React icon)
> 3. We need more fields cc @cychu42 for database input
> 4. We need a drop-down for the Type, one of CNAME Record, A Record, or AAAA Record.  We'll also need some text to explain what each one means, and how to choose
> 
> ## User Dashboard > Edit existing domain
> https://www.figma.com/proto/XAcnMIC1y4qumWinSalHI9/Starchart-UI?node-id=2105%3A2553&scaling=min-zoom&page-id=2105%3A2109
> 
> 1. Need same fields as above
> 2. Need a button to Delete as well as Save
> 3. Need a button to Renew the domain (they will expire otherwise)

I think we should show `created at`, `expire at` and `status` in domains dashboard. I will be ready to provide this data.

**Comment by humphd** [comment]
I think `createdAt` isn't necessary in the "Summary" table, but the expiry would be good, and the `status` can be used to add an icon or something (checkmark vs. x?)

**Comment by Genne23v** [comment]
> I think `createdAt` isn't necessary in the "Summary" table, but the expiry would be good, and the `status` can be used to add an icon or something (checkmark vs. x?)

I like when Vercel or GitHub shows this colour icon. 
<img width="92" alt="Screenshot 2023-01-30 at 8 00 16 PM" src="https://user-images.githubusercontent.com/59734889/215631987-4f846aea-9a80-4db3-ac95-ea2e56e6a547.png">

**Comment by Myrfion** [comment]
@humphd thank you for the review, couple of things that I want to say and clarify:
>maybe I can do it in Figma? I'm not sure. Please educate me

I don't think that there is a standardized way to review the design (PR-like) so this is probably the best way to have everything in one place

> Integrate sidebar menu into top menu. So that we can more easily work on desktop/mobile, why don't we drop the sidebar menu. It only has 2 items, so they could become links in the main nav bar instead.

I fine with both ways, if you know that it is not the matter of time that we gonna have 10 pages, placing them horizontally on the top header is fine


>We won't have an avatar image for the user, so I would get rid of that. We can show their name, or just a generic User Avatar icon if you need one.

I like the idea of having a generic avatar, on the right side so the header doesn't feel empty 


>Question: we have other data about a subdomain (when it expires, the course, description, ports, etc) that we need to be able to show some how. Maybe we show it all here, or maybe you have to Edit or View the record to see it all (i.e., maybe this is just a summary view)? cc @cychu42 for database aspect and @Genne23v for the DNS bits

I am still not sure how many fields each subdomain gonna have (i.e. how many different key-value properties for each subdomain we would show to the user) + I am not sure what fields gonna be editable and which might not. I think when the initial version of the Prisma is gonna be ready it will provide me with some idea about that. In my opinion, it would be like that: the table shows the most important fields in a row (such as status, subdomain name, record type) and then the user might go to details (which is a separate screen) and see more detailed information that gonna include all available information on a certain subdomain. Again, it would be easier to make a visual when the Prisma is ready 


> Need a button to Renew the domain (they will expire otherwise)

Is it gonna be options for what period of time the user renews the domain (e.g year, month, week)?

**Comment by humphd** [comment]
> I don't think that there is a standardized way to review the design (PR-like) so this is probably the best way to have everything in one place

OK, people can continue doing it here.  Maybe on Wednesday you and @Ririio can present it to the whole group for discussion.

> I like the idea of having a generic avatar, on the right side so the header doesn't feel empty

Sounds good.

> > Question: we have other data about a subdomain (when it expires, the course, description, ports, etc) that we need to be able to show some how. Maybe we show it all here, or maybe you have to Edit or View the record to see it all (i.e., maybe this is just a summary view)? cc @cychu42 for database aspect and @Genne23v for the DNS bits

I wonder if we have the summary table show only the main things, and you can click Edit or something to go to a page with a form that shows everything.  For the most part, I can't think people will want to view things unless they want to change it (e.g., you aren't going to need to edit the course name over and over again).

> I am still not sure how many fields each subdomain gonna have (i.e. how many different key-value properties for each subdomain we would show to the user) + I am not sure what fields gonna be editable and which might not. I think when the initial version of the Prisma is gonna be ready it will provide me with some idea about that. In my opinion, it would be like that: the table shows the most important fields in a row (such as status, subdomain name, record type) and then the user might go to details (which is a separate screen) and see more detailed information that gonna include all available information on a certain subdomain. Again, it would be easier to make a visual when the Prisma is ready

I think that's true, but let's attempt a design that includes the ones we are pretty sure are there.  See #59 for my thoughts, and other's evolving ideas.

> Is it gonna be options for what period of time the user renews the domain (e.g year, month, week)?

Users won't have an option about time, only the ability to "Renew."  Likely it will add another 6 months to the lifetime of the domain.

**Comment by Ririio** [comment]
> Users won't have an option about time, only the ability to "Renew." Likely it will add another 6 months to the lifetime of the domain.

I think it would be best to have the renew button shows up on either the table at the domain list, or at the detail's page itself. If we're going to go with the latter, I think it would be the best to have a filter button that displays domains that are currently "inactive" so it would be a lot easier for users to navigate if they have a lot of subdomains under them. This can be in a form of a `switch`. As for the expiration date, should the user be allowed to renew a week before the expiration date so their domain don't close down? Or is that not doable?


> I wonder if we have the summary table show only the main things, and you can click Edit or something to go to a page with a form that shows everything. For the most part, I can't think people will want to view things unless they want to change it (e.g., you aren't going to need to edit the course name over and over again).

Maybe we can have the "name" column be a link to the detail's page (or a hidden div container). The user can view the details of that domain, and press the "edit" button to start editing. We'll have all the extra information within that page like

- description
- creationDate
- ports
- etc

Should the detail's page be a table or should we display the information line by line?

> Integrate sidebar menu into top menu. So that we can more easily work on desktop/mobile, why don't we drop the sidebar menu. It only has 2 items, so they could become links in the main nav bar instead.

I think that's a good idea. We can separate them into multiple sections at the header, and use the [menu](https://chakra-ui.com/docs/components/menu) to group them.

> We need a drop-down for the Type, one of CNAME Record, A Record, or AAAA Record. We'll also need some text to explain what each one means, and how to choose

Chakra actuall has a [popover](https://chakra-ui.com/docs/components/popover) component we can use to make the page a bit more cleaner when it comes to informing users.


I'll work on the detail's page and see if I can figure out a design layout for it before wednesday. I was also wondering if you think we should make the theme similar to blackboard with its black and red aeisthetic @humphd. I think it would give the students and faculty a sense of familiarity if we do so.

**Comment by humphd** [comment]
> I think it would be best to have the renew button shows up on either the table at the domain list, or at the detail's page itself. If we're going to go with the latter, I think it would be the best to have a filter button that displays domains that are currently "inactive" so it would be a lot easier for users to navigate if they have a lot of subdomains under them. This can be in a form of a `switch`. As for the expiration date, should the user be allowed to renew a week before the expiration date so their domain don't close down? Or is that not doable?

I agree.  Having Renew and Delete buttons on the rows in the summary would be helpful.  We can repeat them in the details/form page as well.

I think it's unlikely that students will have a lot of these.  I know Seneca wants to place a limit on the number they can create (imagine it's 20 or something).  When a domain expires, we can likely delete it from Route53 and the database, so it wouldn't show up.

I think you should be able to renew right up to the moment it's going to expire.

> Maybe we can have the "name" column be a link to the detail's page (or a hidden div container). The user can view the details of that domain, and press the "edit" button to start editing. We'll have all the extra information within that page like

Sure, having the name be a link makes sense.  If we do that, you probably don't need an Edit button: clicking the name link could take you to the details page, and you could edit it there.

> Should the detail's page be a table or should we display the information line by line?

I think it should be a form, and if you want to read it, you can; or if you want to edit it, you can.  We'd have an "Update" button as well as "Delete" and "Renew".

> I think that's a good idea. We can separate them into multiple sections at the header, and use the [menu](https://chakra-ui.com/docs/components/menu) to group them.

I don't think you'd need a menu here, since it's literally only 2 items.  We can show the icon + text on screens wide enough to allow both, and only the icon on mobile or something.

> > We need a drop-down for the Type, one of CNAME Record, A Record, or AAAA Record. We'll also need some text to explain what each one means, and how to choose
> 
> Chakra actuall has a [popover](https://chakra-ui.com/docs/components/popover) component we can use to make the page a bit more cleaner when it comes to informing users.

Cool, or you could use [tooltip](https://chakra-ui.com/docs/components/tooltip)

> I'll work on the detail's page and see if I can figure out a design layout for it before wednesday. I was also wondering if you think we should make the theme similar to blackboard with its black and red aeisthetic @humphd. I think it would give the students and faculty a sense of familiarity if we do so.

I don't think you should limit yourself to looking like the worst piece of software in the history of computing (i.e., Blackboard).  Just include red as default colour throughout.

**Comment by Ririio** [comment]
I think leaving a comment on figma would be good too, because it allows you to select which portion of the template you want to discuss

**Comment by humphd** [comment]
Filed #80 for 0.2 on the Certificate pages.

**Comment by humphd** [comment]
We need these designs somehow included in the project repo.  It could be a link to the Figma, or maybe we need to bring screenshots in or in the wiki or something.

**Comment by humphd** [comment]
Also, looking at https://www.figma.com/file/XAcnMIC1y4qumWinSalHI9/Starchart-UI?node-id=2105%3A2109&t=QM0xMcEVyoFatMid-0, not all the screens are done, based on what we discussed in the meeting last Wed.
