### ISSUE TITLE
Create a schema for Prisma

### ISSUE THREAD

**Issue by cychu42** [Seneca-CDOT/starchart#59]
- User table
- Certificate table
- Subdomain table

Reference: https://github.com/Seneca-CDOT/starchart/wiki/Data-Architecture

**Comment by humphd** [comment]
Some of my thoughts from discussing this today with @cychu42.  It would be good to get input from @sfrunza13 (User), @Genne23v (DNS), and @dadolhay (certs) on what they need, too.

## User

I asked ITS about whether we can store and use the User data, and whether or not it is stable.  They said that sometimes it does happen that people will change their name (e.g., get married) but even across Seneca's system, they deal with this manually, and would prefer that here as well.  They are going to look into whether or not AD can give us a GUID, but short of that, the username is what we should use.

- username (pk)
- firstName
- lastName
- fullName
- email
- createdAt, updatedAt (automatic via Prisma/MySQL)

## Domains

I don't know what name we should give these.  Most people will think of them as "Domains" or "Subdomains" and they are technically "Resource Records" in DNS.  Whatever we call them, I think we need:

- id (pk, can be auto-increment)
- username (fk to Users table)
- type (enum: CNAME, A, AAAA)
- name (i.e., the `foo` in `foo.username.starchart.com`)
- value (i.e., the thing the name refers to: an IP address or Domain Name)
- description (free-form text describing what this is being used for)
- course (free-form text to put info about the course this is being used for)
- ports (free-form text to list ports being used)
- createdAt, updatedAt (automatic via Prisma/MySQL)
- expiresAt (when this record should be automatically deleted, unless renewed)

I don't know if we should also include the Canonical DNS Name (i.e., `foo.username.starchart.com.`) as well or not, since we can programmatically construct it from the fields above.

We should also decide about how to record the **state** of the domain.  When we create it, it won't be active yet; after some time, Route53 will sync it. We could include a field to show this, so clients can query for it.

## Certificates

- id (pk, can be auto-increment)
- username (fk to Users table)
- certificate (text of PEM)
- privateKey (text of PEM.  After 0.1, we need to figure out how to encrypt this, but that doesn't have to happen yet)
- subject (the common name(s) of the certificate, e.g., `*.username.starchart.com`)
- validFrom (when it was created)
- validTo (when it will expire)

## Challenges

@dadolhay has mentioned this a few times, and I think he wants to store various state in here so we can do our certificate request process, and update things as we go.  I'll get him to add more info on what he needs.

**Comment by Genne23v** [comment]
> 

I have a couple of questions for DNS fields. 
- I think `ports` is required to access a device that is connected to IP address or domain. I assume this data is validated before storing in database. 
- I think we should also have `status` as some domain might be banned or disabled, or not ready for some reason.
